# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               James Huynh
tagline:             'My little tech blog'
description:         'This is the blog that I always want to devote my time to make it better and informative over time. This also serves as my reference point when in need'
url:                 http://jameshuynh.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              James Huynh 
  url:               https://twitter.com/jameshu
  email:             jameshuynhsg@gmail.com 

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
